# Generated by Django 3.0.5 on 2021-02-11 00:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('price', models.FloatField(verbose_name='preço')),
                ('description', models.TextField(verbose_name='descrição')),
                ('realese_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30, verbose_name='cor')),
                ('size', models.CharField(max_length=2, verbose_name='tamanho')),
                ('stock', models.IntegerField(verbose_name='estoque')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='products.Product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'estoque',
                'verbose_name_plural': 'estoque',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=djongo.storage.GridFSStorage(collection='products_files'), upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='products.Product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'imagem',
                'verbose_name_plural': 'imagens',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nome')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
