# Generated by Django 3.1.5 on 2021-01-19 20:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('price', models.FloatField(verbose_name='preço')),
                ('description', models.TextField(verbose_name='descrição')),
                (
                    'images', django.contrib.postgres.fields.ArrayField(
                        base_field=models.ImageField(upload_to=''), size=None, verbose_name='imagens',
                    ),
                ),
                ('stock', models.JSONField()),
                (
                    'categories', django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), size=None, verbose_name='categorias',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
