# Generated by Django 3.1.7 on 2021-02-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='email',
            new_name='to_email',
        ),
    ]
