version: "3.9"

services:

  postgres:
    image: "postgres:latest"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  mjml:
    image: "liminspace/mjml-tcpserver:latest"
    restart: always
    ports:
      - "28101:28101"

  web:
    build: .
    command: python -m poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:

