# Generated by Django 3.1.4 on 2021-01-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preço', models.FloatField()),
                ('descrição', models.TextField()),
                ('quantidade_de_p', models.IntegerField()),
                ('quantidade_de_m', models.IntegerField()),
                ('quantidade_de_g', models.IntegerField()),
                ('imagem', models.ImageField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
